import jsPDF from "jspdf";

import { AnalysisResult } from "./types";

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function checkPageSpace(doc: jsPDF, y: number, neededSpace = 25): number {
  const pageHeight = doc.internal.pageSize.getHeight();

  if (y + neededSpace > pageHeight - 20) {
    doc.addPage();
    return 20;
  }

  return y;
}

function formatPercent(value: number): string {
  return `${Number(value || 0).toFixed(1)}%`;
}

export function downloadInsightsPdf(result: AnalysisResult): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;

  let y = 18;

  // Header
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 34, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("CommentSurvey AI Report", margin, 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Social media comment insights generated by AI", margin, 25);

  y = 46;

  doc.setTextColor(15, 23, 42);

  // Source / video section
  if (result.source === "youtube") {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("YouTube Video", margin, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    if (result.video_title) {
      y = addWrappedText(doc, `Title: ${result.video_title}`, margin, y, contentWidth, 6);
      y += 2;
    }

    if (result.video_url) {
      y = addWrappedText(doc, `URL: ${result.video_url}`, margin, y, contentWidth, 6);
      y += 2;
    }

    doc.text(
      `Total YouTube Comments: ${
        result.total_youtube_comments?.toLocaleString() ?? "N/A"
      }`,
      margin,
      y
    );
    y += 6;

    doc.text(
      `Analyzed Comments: ${
        result.analyzed_comments?.toLocaleString() ??
        result.total_comments.toLocaleString()
      }`,
      margin,
      y
    );
    y += 8;

    if (result.sample_note) {
      y = addWrappedText(doc, result.sample_note, margin, y, contentWidth, 6);
      y += 4;
    }
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Manual Comment Analysis", margin, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Analyzed Comments: ${result.total_comments.toLocaleString()}`, margin, y);
    y += 10;
  }

  // Overview
  y = checkPageSpace(doc, y, 40);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Opinion Breakdown", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(`Yes: ${formatPercent(result.yes_percentage)}`, margin, y);
  y += 7;
  doc.text(`No: ${formatPercent(result.no_percentage)}`, margin, y);
  y += 7;
  doc.text(`Neutral: ${formatPercent(result.neutral_percentage)}`, margin, y);
  y += 12;

  // Sentiment
  y = checkPageSpace(doc, y, 40);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Sentiment Distribution", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(`Positive: ${formatPercent(result.sentiment.positive)}`, margin, y);
  y += 7;
  doc.text(`Negative: ${formatPercent(result.sentiment.negative)}`, margin, y);
  y += 7;
  doc.text(`Neutral: ${formatPercent(result.sentiment.neutral)}`, margin, y);
  y += 12;

  // Themes
  y = checkPageSpace(doc, y, 40);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Key Themes", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  if (result.themes.length > 0) {
    result.themes.forEach((theme, index) => {
      y = checkPageSpace(doc, y, 10);
      doc.text(`${index + 1}. ${theme}`, margin, y);
      y += 7;
    });
  } else {
    doc.text("No clear themes were detected.", margin, y);
    y += 7;
  }

  y += 5;

  // Summary
  y = checkPageSpace(doc, y, 45);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("AI Summary", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  y = addWrappedText(doc, result.summary || "No summary available.", margin, y, contentWidth, 6);

  // Footer
  const pageCount = doc.getNumberOfPages();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);

    doc.text(
      `Generated by CommentSurvey AI - Page ${page} of ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  const date = new Date().toISOString().slice(0, 10);
  const filename =
    result.source === "youtube"
      ? `youtube-comment-insights-${date}.pdf`
      : `comment-insights-${date}.pdf`;

  doc.save(filename);
}
